"use client";
import {useState,useCallback,useEffect} from "react";
import {useRouter} from "next/navigation";
import {useDropzone} from "react-dropzone";
import {ArrowUpRight,ArrowRight,Upload,FileSpreadsheet,Loader2,Plus,ShieldCheck,ScanLine,Sparkles,Download,Database} from "lucide-react";
import axios from "axios";
type Job={id:string;filename:string;row_count:number;col_count:number;health_score:number;status:string};
export default function Home(){
 const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [jobs,setJobs]=useState<Job[]>([]); const [query,setQuery]=useState('');
 useEffect(()=>{axios.get('/api/jobs').then(r=>setJobs(r.data)).catch(()=>setError('The data service is unavailable. Please try again shortly.'));},[]);
 const upload=useCallback(async(file:File)=>{setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const res=await axios.post('/api/upload',form);router.push(`/dashboard/${res.data.job_id}`);}catch(e){setError(axios.isAxiosError(e)?String(e.response?.data?.detail||'Unable to upload. Please check the data service and try again.'):'Unable to upload this file.');setBusy(false);}},[router]);
 const {getRootProps,getInputProps,isDragActive}=useDropzone({onDrop:files=>{if(files[0])void upload(files[0]);},onDropRejected:()=>setError('Choose one CSV file, up to 20 MB.'),accept:{'text/csv':['.csv']},maxFiles:1,maxSize:20*1024*1024,disabled:busy});
 async function sample(){setBusy(true);setError('');try{const r=await axios.get('/api/sample',{responseType:'blob'});await upload(new File([r.data],'customer_data_sample.csv',{type:'text/csv'}));}catch{setError('Unable to load the sample. Please try again.');setBusy(false);}}
 return <div className="home animate-fade-in-up"><div className="page-heading"><div><div className="eyebrow">A CLEARER PICTURE STARTS HERE</div><h1>Your data, in good health.</h1><p>A little less uncertainty. A lot more confidence in your data.</p></div><a className="button button-dark" href="#upload"><Plus size={16}/> Upload dataset</a></div>
 <div className="welcome-grid"><section className="hero-card"><div className="hero-top"><span><span className="hero-dot"/> YOUR DATA. ALL CONNECTED.</span><ArrowUpRight size={22}/></div><div className="hero-art" aria-hidden="true"><div className="orb orb-one"/><div className="orb orb-two"/><div className="orb orb-three"/></div><div className="hero-copy"><h2>Trust starts<br/>with clarity.</h2><p>Find the gaps. Fix the inconsistencies.<br/>Make every decision a little more certain.</p><button onClick={sample} disabled={busy} className="hero-link">Explore a sample dataset <ArrowUpRight size={18}/></button></div><span className="hero-caption">FROM RAW DATA TO REAL CONFIDENCE</span></section>
 <section id="upload" className={`upload-card ${isDragActive?'dragging':''}`}><div className="card-heading"><span>Bring your data in</span><span className="icon-box"><Plus size={17}/></span></div><div {...getRootProps()} className="drop-area"><input {...getInputProps()} aria-label="Upload CSV dataset"/><div className="upload-icon">{busy?<Loader2 size={28} className="animate-spin"/>:<Upload size={28}/>}</div><h3>{busy?'Preparing your dataset…':isDragActive?'Drop it right here':'A fresh start for your data'}</h3><p>Drag and drop your CSV file here,<br/>or <span>browse files</span> to get started.</p><span className="file-limit">CSV FORMAT · UP TO 20 MB</span></div><div className="upload-foot"><ShieldCheck size={15}/> Your original file stays untouched.</div></section></div>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 <div className="stat-grid"><div className="stat-card"><div><span>Datasets analyzed</span><Database size={17}/></div><strong>{jobs.filter(j=>j.status==='done').length.toString().padStart(2,'0')}</strong><small>Your growing source of clarity</small></div><div className="stat-card"><div><span>Rows explored</span><ScanLine size={17}/></div><strong>{jobs.reduce((n,j)=>n+j.row_count,0).toLocaleString()}</strong><small>Every record tells a story</small></div><div className="stat-card"><div><span>Quality dimensions</span><ShieldCheck size={17}/></div><strong>04<span className="mini-bars">▂ ▄ ▆ █</span></strong><small>One complete picture of your data</small></div></div>
 <section id="datasets" className="dataset-section"><div className="section-heading"><div><h2>Your datasets <span className="count">{jobs.length}</span></h2><p>From the first upload to the final clean file.</p></div><input className="search-input" aria-label="Search datasets" placeholder="Search datasets…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="dataset-table"><div className="table-head"><span>DATASET NAME</span><span>ROWS</span><span>HEALTH SCORE</span><span>STATUS</span><span/></div>{jobs.filter(j=>j.filename.toLowerCase().includes(query.toLowerCase())).map(j=><a key={j.id} className="dataset-row" href={`/dashboard/${j.id}`}><span className="dataset-name"><span className="file-icon"><FileSpreadsheet size={19}/></span><span>{j.filename}<small>{j.col_count} columns · CSV dataset</small></span></span><span>{j.row_count.toLocaleString()}</span><span className="table-score">{j.status==='done'?`${j.health_score} / 100`:'—'}</span><span><span className={`status-pill ${j.status==='error'?'failed':''}`}>{j.status==='done'?'Analyzed':j.status==='error'?'Failed':'Processing'}</span></span><ArrowUpRight size={18}/></a>)}{jobs.length===0&&<div className="empty-datasets"><FileSpreadsheet size={25}/><div><h3>A clean slate, full of possibilities.</h3><p>Upload your first dataset, or take a look around with our sample.</p></div><button disabled={busy} onClick={sample}>Try sample <ArrowRight size={16}/></button></div>}{jobs.length>0&&!jobs.some(j=>j.filename.toLowerCase().includes(query.toLowerCase()))&&<p className="p-6">No datasets match your search.</p>}</div></section>
 <section id="methodology"><div className="section-heading"><div><h2>Good data is a process.</h2><p>Three simple steps. A stronger foundation.</p></div><a href="/api/sample" download className="text-link"><Download size={15}/> Download sample CSV</a></div><div className="process-grid">{([["01","Understand your data","See types, missing values, and patterns at a glance.",ScanLine],["02","Find what needs attention","Spot inconsistencies across four quality dimensions.",ShieldCheck],["03","Make it better","Apply targeted fixes and export a cleaner dataset.",Sparkles]] as const).map(([n,title,desc,Icon])=><div className="process-card" key={String(n)}><div className="process-top"><Icon size={20}/><span>{String(n)}</span></div><h3>{String(title)}</h3><p>{String(desc)}</p></div>)}</div></section></div>
}
