"use client";
import Link from "next/link";
import { useParams, usePathname } from "next/navigation";
import { Activity, LayoutDashboard, Database, Columns3, ShieldCheck, WandSparkles, FileChartColumn, ArrowUpRight, Plus, CircleHelp } from "lucide-react";
export default function Shell({children}:{children:React.ReactNode}) {
 const path=usePathname(); const params=useParams(); const base=params.jobId ? `/dashboard/${params.jobId}` : '';
 const items=base ? [["Overview",base,LayoutDashboard],["Column explorer",`${base}/columns`,Columns3],["Quality issues",`${base}/issues`,ShieldCheck],["Data cleaning",`${base}/cleaning`,WandSparkles],["Export report",`${base}/report`,FileChartColumn]] as const : [["Overview","/",LayoutDashboard],["Your datasets","/#datasets",Database],["How it works","/#methodology",CircleHelp]] as const;
 return <div className="app-shell"><aside className="sidebar"><Link href="/" className="wordmark"><span className="brand-symbol"><Activity size={23}/></span>datahealth<span className="logo-dot">®</span></Link><div className="workspace"><span className="workspace-avatar">W</span><div>My workspace<small>Personal workspace</small></div><span className="workspace-dots">···</span></div><p className="nav-label">WORKSPACE</p><nav>{items.map(([label,href,Icon])=><Link key={label} href={href} className={`nav-item ${path===href?'active':''}`}><Icon size={18}/>{label}{path===href&&<span className="active-dot"/>}</Link>)}</nav><Link href="/" className="new-dataset"><Plus size={17}/> New dataset</Link><div className="sidebar-bottom"><div className="sidebar-note"><span className="tiny-orbit"/><h3>Better data.<br/>Better decisions.</h3><p>A little clarity goes a long way.</p><Link href="/#methodology">Explore the process <ArrowUpRight size={15}/></Link></div><div className="profile"><span>DW</span><div>Data workspace<small>Local environment</small></div><span className="online-dot"/></div></div></aside><div className="main-shell"><header className="topbar"><div><span className="muted">Workspace</span><span className="breadcrumb-slash">/</span>{base?'Dataset analysis':'Overview'}</div><div className="topbar-right"><span className="environment"><span className="online-dot"/> Local workspace</span><span className="top-avatar">DW</span></div></header><main>{children}</main><footer><span>Made for data you can believe in.</span><span>DATAHEALTH <span className="footer-plus">✳</span> CLARITY BY DESIGN</span></footer></div></div>
}
